version: '3'

services:
  mariadb:
    image: mariadb:11.7
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: test
      MYSQL_USER: meowdb
      MYSQL_PASSWORD: 123
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - mariadb_network
    ports:
      - 3306:3306

volumes:
  mariadb_volume:

networks:
  mariadb_network:
    driver: bridge