services:
  mariadb:
    image: mariadb:11.7
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: test
      MYSQL_USER: meowdb
      MYSQL_PASSWORD: 123
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - meow_network
    expose:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  frontend:
    build:
      context: ./frontend
    container_name: frontend
    networks:
      - meow_network
    ports:
      - 80:80


volumes:
  mariadb_volume:

networks:
  meow_network:
    driver: bridge
