services:
  mariadb:
    image: mariadb:11.7
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: test
      MYSQL_USER: meowdb
      MYSQL_PASSWORD: 123
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - meow_network
    expose:
      - 3306:3306

  backend:
    image: ghcr.io/daraghd/meowketplace_backend:latest
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/test
      SPRING_DATASOURCE_USERNAME: meowdb
      SPRING_DATASOURCE_PASSWORD: 123
    networks:
    - meow_network
    ports:
      - 8080:8080
    depends_on:
      - mariadb
  frontend:
    image: ghcr.io/daraghd/meowketplace_frontend:latest
    container_name: frontend
    networks:
      - meow_network
    ports:
      - 80:80

volumes:
  mariadb_volume:

networks:
  meow_network:
    driver: bridge
