services:
  mariadb:
    image: mariadb:11.7
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 123
      MARIADB_DATABASE: test
      MARIADB_USER: meowdb
      MARIADB_PASSWORD: 123
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - meow_network
    ports:
      - 3306:3306

  backend:
    image: ghcr.io/daraghd/meowketplace_backend:latest
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/test
      SPRING_DATASOURCE_USERNAME: meowdb
      SPRING_DATASOURCE_PASSWORD: 123
    networks:
    - meow_network
    ports:
      - 8080:8080
    depends_on:
      - mariadb
    volumes:
      - uploads:/app/uploads

  frontend:
    image: ghcr.io/daraghd/meowketplace_frontend:latest
    container_name: frontend
    environment:
      VITE_API_URL: http://meowketplace.ie/api
    networks:
      - meow_network
    ports:
      - 80:80

volumes:
  mariadb_volume:
  uploads:

networks:
  meow_network:
    driver: bridge
