name: Deploy website

on:
  push:
    paths:
      - 'backend/**'
      - 'frontend/**'
    branches:
      - 'main'
    
jobs:
  build_publish_images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Checkout
        run: |
          docker login --username daraghd --password ${{ secrets.GCR_TOKEN }} ghcr.io
          cd frontend 
          docker build . --tag ghcr.io/daraghd/meowketplace_frontend:latest
          docker push ghcr.io/daraghd/meowketplace_frontend:latest
          cd ../backend
          docker build . --tag ghcr.io/daraghd/meowketplace_backend:latest
          docker push ghcr.io/daraghd/meowketplace_backend:latest

  rebuild_backend_frontend:
    runs-on: ubuntu-latest

    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd meowketplace
          git pull
          docker compose down
          docker compose up --pull always -d
